services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: megapolis
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d megapolis"]
      interval: 5s
      timeout: 3s
      retries: 10

  # formbricks_db:
  #   image: pgvector/pgvector:pg16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: formbricks
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - formbricks_db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d formbricks"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 10


  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app

  # formbricks:
  #   image: rishabhg71/formbricks:latest
  #   depends_on:
  #     formbricks_db:
  #       condition: service_healthy
  #   env_file:
  #     - .env.example.formbricks
  #   environment:
  #     DATABASE_URL: postgresql://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@formbricks_db:5432/${PGDATABASE:-formbricks}?schema=public
  #     ENCRYPTION_KEY: ${ENCRYPTION_KEY}
  #     WEBAPP_URL: ${WEBAPP_URL:-http://localhost:3000}
  #     NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
  #     NODE_ENV: production
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - uploads:/home/nextjs/apps/web/uploads




volumes:
  db_data:
  formbricks_db_data:
  uploads:
    driver: local
